export const actionTypes = {
  ON_SUCCESS: "ON_SUCCESS",
  ON_FAILURE: "ON_FAILURE",
  ON_CHANGE_QUERY: "ON_CHANGE_QUERY",
  ON_PROGRESS: "ON_PROGRESS",
  DISPLAY_BAR: "DISPLAY_BAR",
  PAGE_INCREMENT: "PAGE_INCREMENT",
  PAGE_DECREMENT: " PAGE_DECREMENT",
  SET_INPUT_ERROR: "SET_INPUT_ERROR",
  SET_SUGGESTION_TEXT: "SET_SUGGESTION_TEXT",
};
